### ISSUE TITLE
Extend tenant example with automatic deployment

### ISSUE THREAD

**Issue by Arend-Jan** [kpn-dsh/dsh-sdk-platform-rs#12]
In the tenant service example, there is a make file which build you container and pushes it to the registry. It would be very cool, if it could also use the DSH REST api, to deploy the service to the platform if you want to as well.

**Comment by toelo3** [comment]
Currently looking into the deployment via the make file and added a WIP in [feature/enhance_example_service](https://github.com/kpn-dsh/dsh-sdk-platform-rs/tree/feature/enhance_example_service)

Idea is when "make all" or "make deploy" is executed, it will ask for some details like client_secret and platform to deploy to. Then it will execute a bash script to do the appropriate rest calls
