### ISSUE TITLE
dsh example - log output

### ISSUE THREAD

**Issue by Arend-Jan** [kpn-dsh/dsh-sdk-platform-rs#14]
please also add at leas a log output that it has started (no log at all if it starts). might be good also to take a look at the default logger

**Comment by toelo3** [comment]
i would then suggest the following
- [ ] replace println's inside the DSH_SDK with proper logging via [log](https://crates.io/crates/log)
- [ ] add [env_logger](https://crates.io/crates/env_logger) to the DSH service example and set logging to stdout
- [ ] based on result of initiating SDK add a logging line that it has started

**Comment by toelo3** [comment]
Changes are currently in the [feature/enhance_example_service](https://github.com/kpn-dsh/dsh-sdk-platform-rs/tree/feature/enhance_example_service) branch.
