### ISSUE TITLE
Support for DSH VPN

### ISSUE THREAD

**Issue by abijithanikkuruthi** [kpn-dsh/dsh-sdk-platform-rs#36]
- Ability to connect to DSH Kafka cluster via DSH VPN
- The order of connectivity/fallback could be: a) DSH Kafka Cluster, b) DSH VPN c) Local Deployment
- DSH VPN connectivity mode could be via an environment variable that could have the following values: "dsh" or "dsh-vpn" or "local"
- If the env variable is not set, by default, it'll try DSH Kafka, then DSH VPN and then local
- If the value is set, but unable to connect, it should raise a connection exception

**Comment by abijithanikkuruthi** [comment]
Currently, not feasible with the current setup of VPN scripts.

**Comment by toelo3** [comment]
Steps to add this support:
- Add load keys/pem files from PKI_CONFIG_DIR
- Add script to VPN repo to convert JKS to keys/pem file
- Check for set env variables

**Comment by toelo3** [comment]
Supported per version 0.4.1

**Comment by toelo3** [comment]
Supported per version 0.4.1
